---
- name: Install Apache on Ubuntu
  ansible.builtin.package:
    name: apache2
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Start and enable Apache service on Ubuntu
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install PHP on Ubuntu
  ansible.builtin.package:
    name: php
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Start and enable MariaDB on Ubuntu
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: yes
  when: ansible_distribution == 'Ubuntu'
