---
- name: Install Prometheus on CentOS Server
  ansible.builtin.shell: |
    sudo dnf makecache
    sudo dnf install -y prometheus
  when: ansible_distribution == 'CentOS'
  become: yes

- name: Start and enable Prometheus service on CentOS Server
  ansible.builtin.service:
    name: prometheus
    state: started
    enabled: yes
  when: ansible_distribution == 'CentOS'
  become: yes
